update typing, list dependencies in readme
lovering810/plumbingbird pull request #4
Opened 2024-02-25 15:52 UTC by abargar

Fixing some small typing errors in several files, typically where Optional needed to be added.

Also added installation dependencies to the readme.

2024-02-25 16:06 UTC, lovering810 requested changes
Tiny addition to docs (links to install), otherwise bang on, thank you, good fixes.

2024-02-25 16:06 UTC, lovering810 commented on orchestration/aws/infra.py
> +    def listen(self, callback: Callable[[dict[str, Any]], None]):
🤦🏻‍♀️ good catch, I got so high on getting rid of Typing with generics that I went too far.

2024-02-25 16:06 UTC, lovering810 commented on README.md
> +1. `postgresql`
Propose making these hyperlinks to install docs for each:

1. [postgresql](https://www.postgresql.org/download/)
2. [poetry](https://python-poetry.org/docs/#installation)

2024-02-26 07:51 UTC, abargar commented on README.md
> +1. `postgresql`
```suggestion
1. `[postgresql](https://www.postgresql.org/download/)`
```

2024-02-26 07:51 UTC, abargar commented on README.md
> +2. `poetry`
```suggestion
2. `[poetry](https://python-poetry.org/docs/#installation)`
```

2024-02-26 13:29 UTC, lovering810 approved these changes
🥳

2024-02-26 15:33 UTC, merged